# Generated by Django 3.2.19 on 2023-05-08 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('subheading', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=250)),
                ('post_image', models.ImageField(blank=True, default='../adventure_default_xreot1', upload_to='images/')),
                ('family_friendly', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='none', max_length=8)),
                ('all_weather', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='none', max_length=8)),
                ('terrain_challenge', models.CharField(choices=[('smooth sailing', 'Smooth sailing'), ('a little bumpy', 'A little bumpy'), ('climbing required', 'Climbing required'), ('a real challenge', 'A real challenge!')], default='none', max_length=30)),
                ('cost', models.CharField(choices=[('free', 'Free'), ('£', '£'), ('££', '££'), ('£££', '£££')], default='none', max_length=8)),
                ('duration', models.CharField(choices=[('< 1 hour', '< 1 hour'), ('a few hours', 'A few hours'), ('half-day', 'Half-day'), ('full-day', 'Full-day')], default='none', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
